SELECT * FROM MY_ECOMMERCE_DB.PUBLIC.GOLD_CATEGORY_SALES ORDER BY TOTAL_REVENUE DESC;

SELECT COUNT(*) AS TOTAL_CATEGORIES FROM MY_ECOMMERCE_DB.PUBLIC.GOLD_CATEGORY_SALES;

SELECT 
    COUNT(CASE WHEN PRODUCT_CATEGORY IS NULL THEN 1 END) AS NULL_CATEGORIES,
    COUNT(CASE WHEN TOTAL_REVENUE IS NULL THEN 1 END) AS NULL_REVENUE
FROM MY_ECOMMERCE_DB.PUBLIC.GOLD_CATEGORY_SALES;
